# Generated by Django 5.1.4 on 2024-12-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimap_app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
